### ISSUE TITLE
Question: MrMAPI, proper use of -RFC822 flag in MAPI->MIME conversion

### ISSUE THREAD

**Issue by mpknemo** [stephenegriffin/mfcmapi#114]
Hi, 

Conversion works fine with command line like this:

C:\MrMAPI.exe.18.0.18058.06\MrMAPI.exe -Mi -I C:\MsgFile.msg -O C:\EmlFile.eml

But when trying to get the eml file in RFC822 format it wont convert (lists -? contents). I tried adding the flag everywhere for example:

C:\MrMAPI.exe.18.0.18058.06\MrMAPI.exe -Mi -I C:\MsgFile.msg -O C:\EmlFile.eml -Rf

What am I doing wrong? 

Thanks in advance
Markus

**Comment by stephenegriffin** [comment]
Think I may see the problem. This:
`{ switchRFC822, cmdmodeMAPIMIME, 1, 1, 0 },`
indicates the switch takes 1 argument. It probably should have been this:
`{ switchRFC822, cmdmodeMAPIMIME, 0, 0, 0 },`

If you wanna test the change and then submit a PR, I'll accept it. Otherwise I'll try to get to it myself soon

**Comment by mpknemo** [comment]
I did the conversion successfully by adding an argument ("1").

C:\MrMAPI.exe.18.0.18058.06\MrMAPI.exe -Mi -I C:\MsgFile.msg -O C:\EmlFile.eml -Rf 1

Thanks
Markus

**Comment by stephenegriffin** [comment]
Thanks for checking - using this as a test case for my new appveyor CI. :)
