### ISSUE TITLE
Outlook version Detection On Centennial

### ISSUE THREAD

**Issue by stephenegriffin** [stephenegriffin/mfcmapi#124]
1. Install Office from Store
2. Tools/Outlook Version

Expected:
Version #

Actual:
Outlook does not appear to be installed on this machine.

**Comment by desjarlais** [comment]
You could try FindPackagesByPackageFamily API:

https://msdn.microsoft.com/en-us/library/windows/desktop/dn270601(v=vs.85).aspx

I did a test with GetPackageFamilyName and it returned "Microsoft.Office.Desktop_8wekyb3d8bbwe" for all Office Centennial apps.  When I pass that into FindPackagesByPackageFamily it returns "No packages found" or it succeeds, so that might be an option.

**Comment by stephenegriffin** [comment]
Thanks Brandon!
