### ISSUE TITLE
Address Book Dialog Missing Icons

### ISSUE THREAD

**Issue by stephenegriffin** [stephenegriffin/mfcmapi#153]
Likely an Outlook bug, but logging so I can investigate
Repro Steps:
1. Quick Start/Address Book/Look up user

Expected: Address book has icons
Actual: So much orange dot

**Comment by dmitry007** [comment]
The issue is calling IAddrBook::Address outside of the outlook.exe address space. The following Redemption script shows the icons correctly when running inside Outlook (I used Script in OutlookSpy, or you can use Outlook VBA editor). The same script running from a standalone VBS file misses icons as well (just like MFCMAPI).
Looks like some dll with the icon resources is only getting loaded when running under Outlook...

  set Session = CreateObject("Redemption.RDOSession")
  Session.Logon
  set AB = Session.AddressBook
  set Recips = AB.ShowAddressBook
![mfcmapi](https://user-images.githubusercontent.com/2702574/41551017-10ef35da-731a-11e8-891b-c4b4e3dacd8b.jpg)
![in_outlook](https://user-images.githubusercontent.com/2702574/41551018-110c48d2-731a-11e8-85c8-47901effb6dd.jpg)

**Comment by stephenegriffin** [comment]
Previously reported by Alexei in #55 (I *thought* I had seen this before).

**Comment by stephenegriffin** [comment]
Figured out so far that we don't have a resource handle where Outlook does have one. Now to debug Outlook and see where it got the handle.

**Comment by stephenegriffin** [comment]
Still repros with 16.0.11001.20108

**Comment by stephenegriffin** [comment]
This works now
