### ISSUE TITLE
Code: MAPI_W_PARTIAL_COMPLETION == 0x00040680

### ISSUE THREAD

**Issue by johnmeco** [stephenegriffin/mfcmapi#416]
how do I get help with this error code?

**Comment by stephenegriffin** [comment]
That code means the server/message store was asked to do multiple things (like delete or move) and was able to accomplish between zero and all of them. And also that it did not return an error.

**Comment by johnmeco** [comment]
How do I delete the message? I keep getting this error when I try to delete it.

**Comment by bradhugh** [comment]
It seems to indicate that the message store (or server) is failing to delete the message.  The error doesn't tell you enough to now why the delete is failing.  

If this is connected to Exchange, the most common reasons for delete failure are:
1) Recoverable Items is over quota (so you can't delete any more)
2) The message is marked for submit. (Common especially if the message is in sent items or drafts). You could try using MFCMapi's "abort submit" feature to unmark the message from submit, then see if it lets you delete it.

Otherwise, you'd have to get someone (probably support) to help you figure that out.

**Comment by johnmeco** [comment]
The "abort submit" worked beautifully. Thank you so much!
