### ISSUE TITLE
Crashing - MFCMAPI X86 Has Stopped Working

### ISSUE THREAD

**Issue by ckraimer** [stephenegriffin/mfcmapi#50]
I saved my autocomplete list on the old Win 7 computer and now need to restore it on a Win 10 Pro 64 bit machine with all the latest MS updates. When I run MFC MAPI it opens - and then when I click Session Logon it crashes with the error "MFCMAPI X86 Has Stopped Working". I've tried running as admin, running in compatibility mode, etc, etc. please help as I need to restore this list. This is with Outlook 2016 32bit.

**Comment by stephenegriffin** [comment]
Look at this thread: https://github.com/stephenegriffin/mfcmapi/issues/48

**Comment by ckraimer** [comment]
I don't have any "bigger issues with Win 10" as the person in thread #48  - I ran MFCMAPI again and it let me logon this time, but when it came time to deleting the autocomplete list it crashes every time and won't delete the list. I've tried run MFCMAPI with Outlook running and with it closed. I'll try a delayed release of Office now as you suggest in thread #48.

**Comment by stephenegriffin** [comment]
_This is a canned reply_
You have reported a crash. In order to best investigate this report, here is what I need:

1. Exact repro steps. Don't assume I know the steps you followed, or that I would use the same steps that you would.
2. Event log information. Don't upload your evtx files - I won't open them. Don't post a screenshot of your event log either - it's annoying to have to retype hex. Instead, copy/paste the 1000 or 1001 events as text. #48 is a perfect example of how to post event information, especially an event that includes a bucket number.
3. Exact build numbers for Outlook and MFCMAPI.

In my experience, most crashes in MFCMAPI are NOT the fault of MFCMAPI. Most crashes in MFCMAPI are bugs in MAPI itself (I can confirm this from my Watson reports). If you've really found a bug in MFCMAPI, I'll do my best to address it.

**Comment by stephenegriffin** [comment]
No details - not MFCMAPI

**Comment by SammyKrosoft** [comment]
Same here ... crashes on Windows 2008 R2 server, Windows 7 as well, both x86 and x64 when choosing Profile -> Advanced profile -> Add services to MAPISVC.inf : 

![image](https://user-images.githubusercontent.com/33433229/32462389-32034068-c307-11e7-83c4-a40513e34036.png)

Then check "Exchange" : 
![image](https://user-images.githubusercontent.com/33433229/32462441-515b53d8-c307-11e7-9537-abf6068fe6c5.png)

Then getting the crash : 
![image](https://user-images.githubusercontent.com/33433229/32462453-5de1fd1e-c307-11e7-9e53-1e93105262cb.png)


Sam
