### ISSUE TITLE
Logon with MapiHttp profile

### ISSUE THREAD

**Issue by alt160** [stephenegriffin/mfcmapi#51]
Steve,

if i create a new outlook profile (OL2010) that uses Mapi/Http, MFCMAPI crashes with Sesssion/Logon.
However, outlook is able to open and use the profile just fine.

i know that i have a Mapi/Http profile due to the following:
1. server is enabled.
2. connection status in outlook shows it.
3. profile details show entries for https://server.name/mapi/emsmdb/?MailboxId=
4. Outlook is [obviously from #2] properly patched/updated to support mapi/http.

is an application not able to use mapi/http separate from outlook?  i'm trying to change my connections in an application to use mapi/http, but even a simple logon (outside of MFCMAPI) also crashes.

Regards,
Eriq VanBibber

**Comment by stephenegriffin** [comment]
_This is a canned reply_
You have reported a crash. In order to best investigate this report, here is what I need:

1. Exact repro steps. Don't assume I know the steps you followed, or that I would use the same steps that you would.
2. Event log information. Don't upload your evtx files - I won't open them. Don't post a screenshot of your event log either - it's annoying to have to retype hex. Instead, copy/paste the 1000 or 1001 events as text. #48 is a perfect example of how to post event information, especially an event that includes a bucket number.
3. Exact build numbers for Outlook and MFCMAPI.

In my experience, most crashes in MFCMAPI are NOT the fault of MFCMAPI. Most crashes in MFCMAPI are bugs in MAPI itself (I can confirm this from my Watson reports). If you've really found a bug in MFCMAPI, I'll do my best to address it.

**Comment by alt160** [comment]
so, found this support article that exposes that it is/was a bug.
https://support.microsoft.com/en-us/help/3050312/program-crashes-when-you-send-an-attachment-through-outlook

specifically from the article:
Note In this same configuration, MFCMAPI.exe crashes when you try to open your mailbox by using the MFCMAPI tool. In that case, the crash signature details match those provided in the preceding sample, and the Application Name value is Mfcmapi.exe.

however, i have an update after the one suggested and still have the issue.  i also tried resetting my VM and using the explicit udpate mentioned and mapi still has an issue.

so, your canned reply was right :), it's a mapi bug!  but it doesn't seem to be fixed.
not sure what to do from here :(.

**Comment by stephenegriffin** [comment]
This should be fixed in Outlook by now
