### ISSUE TITLE
Crash on converting EML to MSG

### ISSUE THREAD

**Issue by thims** [stephenegriffin/mfcmapi#54]
After the Outlook 2016 update v1706 this function crashes every time on any EML provided!

**Comment by stephenegriffin** [comment]
Same as #52

**Comment by thims** [comment]
Actually, this is not duplicate. The #52 is about MSG->EML conversion. But this is about EML->MSG.

**Comment by stephenegriffin** [comment]
Point taken!

_This is a canned reply_
You have reported a crash. In order to best investigate this report, here is what I need:

1. Exact repro steps. Don't assume I know the steps you followed, or that I would use the same steps that you would.
2. Event log information. Don't upload your evtx files - I won't open them. Don't post a screenshot of your event log either - it's annoying to have to retype hex. Instead, copy/paste the 1000 or 1001 events as text. #48 is a perfect example of how to post event information, especially an event that includes a bucket number.
3. Exact build numbers for Outlook and MFCMAPI.

In my experience, most crashes in MFCMAPI are NOT the fault of MFCMAPI. Most crashes in MFCMAPI are bugs in MAPI itself (I can confirm this from my Watson reports). If you've really found a bug in MFCMAPI, I'll do my best to address it.

**Comment by stephenegriffin** [comment]
Also, @thims, exactly which function are you saying crashes?

**Comment by thims** [comment]
In MFCMAPI 17.0.17099.01:
1. Advanced -> Import / Export -> Convert EML to MSG...
2. All defaults and OK.
3. Select any EML file and specify the target MSG file name.
4. Crash.

Outlook 2016 16.0.8229.2086 x86 on Windows 10 1703.15063.413. But this also happens on newer Outlook (Insider Fast).

**Comment by jacobx1** [comment]
I have also seen this issue in MFCMAPI and my own MAPI Provider code.

If it helps, I only get the crash on the `IConverterSession::MIMEToMAPI` call when done outside of the Outlook process. If done in the provider while Outlook has it loaded - works fine. Perhaps OUTLMIME expects something from the C2R bubble/registry or Outlook process?

Outlook 2016 - v1706 - Build: 8229.2103 (x64)

**Comment by stephenegriffin** [comment]
@thims, when I try those steps, I get the error I expect to see:
Error: IConverterSession not found. This interface is only supported by Outlook 2003 and higher.
Code: REGDB_E_CLASSNOTREG == 0x80040154
Function CoCreateInstance(CLSID_IConverterSession, nullptr, CLSCTX_INPROC_SERVER, IID_IConverterSession, reinterpret_cast<LPVOID*>(&lpConverter))
File MapiMime.cpp
Line 27

Have you done something to try and register IConverterSession outside of the C2R bubble?

**Comment by thims** [comment]
No. It just crashes on a clean Windows 10 (and Windows 7) + Office 365 (and Office 2016 ProPlus) installation (all with latest updates).

**Comment by stephenegriffin** [comment]
Ok. Then this clearly isn't an issue with MFCMAPI.
