### ISSUE TITLE
Confused: PropTag > = 0x8000 still no named property!? (technical quesition)

### ISSUE THREAD

**Issue by DevMichaelSabo** [stephenegriffin/mfcmapi#59]
Hello Mr. Griffin

I'm a little bit confused. Perhaps do you know the answer.

If you open a RESOLVED RECIPIENT (steps I wrote in issue #56) of an office 365/exchange postbox, you get a long list of properties. Many of them are over 0x8000 (e.g. PR_EMS_AB_AUTH_ORIG).

Normally named prop tags are dynamically and must be translated with GetNamesFromIDs and 
GetIDsFromNames. But the class IMailUser don't implement GetNamesFromIDs (E_NOT_IMPL). 
See also https://msdn.microsoft.com/en-us/library/ms629504(v=vs.85).aspx

But the documentation is contradictory.

> The range for named property identifiers is between 0x8000 and 0xFFFE.

https://msdn.microsoft.com/en-us/library/office/cc765864.aspx

> To support named properties, a service provider implements two methods — IMAPIProp::GetIDsFromNames and IMAPIProp::GetNamesFromIDs — to translate between names and identifiers and to allow its IMAPIProp::GetPropsIMAPIProp::SetProps methods to retrieve and modify properties with identifiers in the named property range.

https://msdn.microsoft.com/en-us/library/office/cc765864.aspx

I see MFCMAPI already don't show/resolve named props of these object (no data in column named prop)

Are this properties now named props, or not? Why isn't the function GetNamesFromIDs  not available for IMailUsers?

Thanks

**Comment by stephenegriffin** [comment]
The address book doesn't support named properties (I suppose some third party AB could, but none of ours do). They use properties over 8000 directly, without any mapping. You can recognize this when you see properties starting with PR_EMS_AB, as you do in this case.

BTW, when MFCMAPI knows it's dealing with an AB entry, it stops doing GetNamesFromIDs and does prop tag mapping instead. However, there are some scenarios where MFCMAPI can end up with an item and not know that it's an AB item. Some of these scenarios are bugs in MFCMAPI since I *could* have known, but some are unavoidable. The scenario you outlined appears to be working correctly.

**Comment by DevMichaelSabo** [comment]
Thanks
